apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redcarpet-server-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws
  target:
    name: cluster-secrets # Secret name in k8s
    creationPolicy: Owner
  data:
    - secretKey: password # which key it's going to be stored
      remoteRef:
        key: super-secret # Our secret-name goes here

